backend:
  name: git-gateway
media_folder: src/assets/images
public_folder: /assets/images
collections:
- name: posts
  label: Reviews
  folder: src/posts
  create: true
  fields:
  - {label: Titulo,name: title,widget: string}
  - {label: Nota,name: rating,widget: number}
  - {label: Categoria,name: category,widget: select,options:[Anime,Dorama,Kdrama]}
  - {label: Texto,name: body,widget: markdown}